main : main.c code/affichage.c code/init.c code/logique.c code/JvsJ.c code/menu.c code/load.c code/IA.c code/IAvsJ.c
	gcc -fcommon -Wall main.c code/affichage.c code/init.c code/JvsJ.c code/logique.c code/menu.c code/load.c code/IA.c code/IAvsJ.c -o main -lSDL2 -lSDL2_image -lSDL2_ttf -lm -g
clean :
	rm main
