main : main.c code/affichage.c code/init.c code/logique.c code/game.c code/menu.c
	gcc -fcommon -Wall main.c code/affichage.c code/init.c code/game.c code/logique.c code/menu.c -o main -lSDL2 -lSDL2_image -lSDL2_ttf
clean :
	rm main
