main : main.c code/affichage.c code/init.c code/logique.c code/JvsJ.c code/menu.c code/load.c 
	gcc -fcommon -Wall main.c code/affichage.c code/init.c code/JvsJ.c code/logique.c code/menu.c code/load.c  -o main -lSDL2 -lSDL2_image -lSDL2_ttf
clean :
	rm main
